/**
 * AI Trading Copilot
 * 
 * Uses Ollama as the local AI layer. The AI NEVER invents financial facts —
 * it only receives structured context generated by ProTrader's engines:
 * 
 * Market Data → Indicators → Regime → Portfolio → News → Structured Context → Ollama → Explanation
 * 
 * Every AI response includes an auditable evidence panel:
 * - Data used (indicators, market conditions, portfolio context)
 * - Risks and counterarguments
 * - Confidence
 * - Timestamp and data freshness
 * 
 * Falls back to a rule-based analysis engine when Ollama is unavailable.
 */
const axios = require('axios');

class AICopilot {
    constructor(config = {}) {
        this.ollamaUrl = config.ollamaUrl || process.env.OLLAMA_URL || 'http://localhost:11434';
        this.model = config.model || process.env.OLLAMA_MODEL || 'llama3.2';
        this.timeout = config.timeout || 30000;
        this.cache = new Map();
        this.cacheTTL = config.cacheTTL || 60000;
        this.enabled = config.enabled !== false;
    }

    /**
     * Check if Ollama is reachable
     */
    async isOllamaAvailable() {
        try {
            const response = await axios.get(`${this.ollamaUrl}/api/tags`, { timeout: 2000 });
            return response.status === 200;
        } catch (e) {
            return false;
        }
    }

    /**
     * Analyze an instrument using structured context
     * @param {object} context - Structured context from engines
     */
    async analyze(context) {
        const cacheKey = JSON.stringify(context).slice(0, 500);
        const cached = this.cache.get(cacheKey);
        if (cached && Date.now() - cached.timestamp < this.cacheTTL) {
            return cached;
        }

        // Build the auditable evidence panel from structured context
        const evidence = this._buildEvidence(context);

        let aiExplanation = null;
        const ollamaAvailable = this.enabled && await this.isOllamaAvailable();

        if (ollamaAvailable) {
            aiExplanation = await this._callOllama(context, evidence);
        }

        // Always generate rule-based analysis as the factual baseline
        const ruleAnalysis = this._ruleBasedAnalysis(context, evidence);

        const result = {
            symbol: context.symbol,
            signal: ruleAnalysis.signal,
            bias: ruleAnalysis.bias,
            evidence,
            explanation: aiExplanation || ruleAnalysis.explanation,
            aiModel: aiExplanation ? `ollama:${this.model}` : 'rule-engine',
            confidence: ruleAnalysis.confidence,
            risks: evidence.risks,
            counterarguments: evidence.counterarguments,
            invalidation: evidence.invalidation,
            timestamp: new Date().toISOString(),
            dataFreshness: context.dataTimestamp || new Date().toISOString(),
            disclaimer: 'AI analysis is generated from structured market data. It is not investment advice.'
        };

        this.cache.set(cacheKey, { ...result, timestamp: Date.now() });
        return result;
    }

    _buildEvidence(context) {
        const indicators = context.indicators || {};
        const regime = context.regime || {};
        const marketData = context.marketData || {};
        const portfolio = context.portfolio || {};

        const evidence = {
            indicatorsUsed: {
                rsi: indicators.rsi !== undefined ? parseFloat(indicators.rsi.toFixed(2)) : null,
                macdHistogram: indicators.macdHistogram !== undefined ? parseFloat(indicators.macdHistogram.toFixed(3)) : null,
                ema20: indicators.ema20 !== undefined ? parseFloat(indicators.ema20.toFixed(2)) : null,
                ema50: indicators.ema50 !== undefined ? parseFloat(indicators.ema50.toFixed(2)) : null,
                ema200: indicators.ema200 !== undefined ? parseFloat(indicators.ema200.toFixed(2)) : null,
                atr: indicators.atr !== undefined ? parseFloat(indicators.atr.toFixed(2)) : null,
                adx: indicators.adx !== undefined ? parseFloat(indicators.adx.toFixed(1)) : null
            },
            marketConditions: {
                regime: regime.regime || 'UNKNOWN',
                regimeSub: regime.sub || '',
                volatility: marketData.volatility !== undefined ? parseFloat((marketData.volatility * 100).toFixed(2)) : null,
                relativeVolume: marketData.relativeVolume !== undefined ? parseFloat(marketData.relativeVolume.toFixed(2)) : null,
                price: marketData.price !== undefined ? parseFloat(marketData.price.toFixed(2)) : null
            },
            portfolioContext: {
                totalValue: portfolio.totalValue,
                symbolExposure: portfolio.symbolExposure,
                concentrationRisk: portfolio.concentrationRisk
            },
            risks: this._deriveRisks(indicators, regime, marketData),
            counterarguments: this._deriveCounterarguments(indicators, marketData),
            invalidation: this._deriveInvalidation(marketData, indicators)
        };

        return evidence;
    }

    _deriveRisks(indicators, regime, marketData) {
        const risks = [];
        if (regime.regime === 'HIGH VOLATILITY') risks.push('Elevated volatility increases downside risk');
        if (indicators.rsi !== undefined && indicators.rsi > 70) risks.push('RSI indicates overbought conditions');
        if (indicators.rsi !== undefined && indicators.rsi < 30) risks.push('RSI indicates oversold conditions');
        if (marketData.relativeVolume !== undefined && marketData.relativeVolume > 2) {
            risks.push('Unusually high volume — move may be exhausted');
        }
        if (regime.regime === 'TRENDING' && regime.sub === 'BEARISH') risks.push('Market regime is bearish');
        if (risks.length === 0) risks.push('No immediate risk flags from available data');
        return risks;
    }

    _deriveCounterarguments(indicators, marketData) {
        const counter = [];
        const price = marketData.price;
        if (indicators.rsi !== undefined && indicators.rsi > 60 && price && price > indicators.ema200) {
            counter.push('Price extended above 200 EMA — mean reversion possible');
        }
        if (price && price < indicators.ema200) {
            counter.push('Price below 200 EMA — long-term trend not supportive');
        }
        if (indicators.adx !== undefined && indicators.adx < 20) {
            counter.push('Weak directional strength (ADX) — trend may be unreliable');
        }
        return counter;
    }

    _deriveInvalidation(marketData, indicators) {
        const conditions = [];
        if (marketData.price && indicators.ema20) {
            conditions.push(`Close below ${parseFloat(indicators.ema20.toFixed(2))} (20 EMA)`);
        }
        if (marketData.price && indicators.ema50) {
            conditions.push(`Close below ${parseFloat(indicators.ema50.toFixed(2))} (50 EMA)`);
        }
        return conditions;
    }

    /**
     * Rule-based analysis — the factual baseline that never invents data
     */
    _ruleBasedAnalysis(context, evidence) {
        const { indicators = {}, marketData = {}, regime = {} } = context;

        let bullishScore = 0;
        let bearishScore = 0;
        const reasons = [];

        const price = marketData.price;
        const rsi = indicators.rsi;
        const macdH = indicators.macdHistogram;
        const ema20 = indicators.ema20;
        const ema50 = indicators.ema50;
        const ema200 = indicators.ema200;

        // Trend
        if (price && ema200) {
            if (price > ema200) { bullishScore += 2; reasons.push(`Price (${price.toFixed(2)}) is above 200 EMA (${ema200.toFixed(2)})`); }
            else { bearishScore += 2; reasons.push(`Price (${price.toFixed(2)}) is below 200 EMA (${ema200.toFixed(2)})`); }
        }
        if (price && ema50) {
            if (price > ema50) { bullishScore += 1; reasons.push('Price is above 50 EMA'); }
            else { bearishScore += 1; reasons.push('Price is below 50 EMA'); }
        }
        // Momentum
        if (rsi !== undefined) {
            if (rsi > 55 && rsi < 70) { bullishScore += 1; reasons.push(`RSI ${rsi.toFixed(1)} shows healthy momentum`); }
            else if (rsi >= 70) { bearishScore += 1; reasons.push(`RSI ${rsi.toFixed(1)} is overbought`); }
            else if (rsi < 35) { bearishScore += 1; reasons.push(`RSI ${rsi.toFixed(1)} is weak`); }
            else { reasons.push(`RSI ${rsi.toFixed(1)} is neutral`); }
        }
        // MACD
        if (macdH !== undefined) {
            if (macdH > 0) { bullishScore += 1; reasons.push('MACD histogram is positive'); }
            else { bearishScore += 1; reasons.push('MACD histogram is negative'); }
        }
        // Volume
        if (marketData.relativeVolume !== undefined) {
            if (marketData.relativeVolume > 1.5) reasons.push(`Relative volume is ${marketData.relativeVolume.toFixed(1)}x — move is confirmed by volume`);
            if (marketData.relativeVolume > 1.5 && bearishScore > bullishScore) { bearishScore += 1; }
        }
        // Regime
        if (regime.regime === 'TRENDING' && regime.sub === 'BULLISH') { bullishScore += 1; reasons.push('Market regime is bullish'); }
        if (regime.regime === 'TRENDING' && regime.sub === 'BEARISH') { bearishScore += 1; reasons.push('Market regime is bearish'); }
        if (regime.regime === 'HIGH VOLATILITY') { bearishScore += 1; reasons.push('High volatility environment'); }

        // Signal
        let signal = 'NEUTRAL', bias = 'Neutral';
        const net = bullishScore - bearishScore;
        if (net >= 3) { signal = 'BULLISH'; bias = 'Bullish bias'; }
        else if (net >= 1) { signal = 'MILD_BULLISH'; bias = 'Slightly bullish'; }
        else if (net <= -3) { signal = 'BEARISH'; bias = 'Bearish bias'; }
        else if (net <= -1) { signal = 'MILD_BEARISH'; bias = 'Slightly bearish'; }

        const confidence = Math.min(0.9, Math.max(0.35, 0.5 + Math.abs(net) * 0.08));

        const explanation = this._composeExplanation(bias, reasons, evidence);

        return { signal, bias, explanation, confidence };
    }

    _composeExplanation(bias, reasons, evidence) {
        const lines = [];
        lines.push(`Analysis for ${evidence.marketConditions.price ? 'current price levels' : 'the instrument'}:`);
        lines.push(`${bias}.`);
        lines.push('');
        lines.push('Supporting evidence:');
        reasons.slice(0, 5).forEach(r => lines.push(`• ${r}`));
        if (evidence.risks.length > 0) {
            lines.push('');
            lines.push('Risks:');
            evidence.risks.slice(0, 3).forEach(r => lines.push(`• ${r}`));
        }
        if (evidence.counterarguments.length > 0) {
            lines.push('');
            lines.push('Counterarguments:');
            evidence.counterarguments.slice(0, 2).forEach(c => lines.push(`• ${c}`));
        }
        lines.push('');
        lines.push('This analysis uses only verified structured data. It is not investment advice.');
        return lines.join('\n');
    }

    async _callOllama(context, evidence) {
        const prompt = this._buildPrompt(context, evidence);

        try {
            const response = await axios.post(`${this.ollamaUrl}/api/generate`, {
                model: this.model,
                prompt,
                stream: false,
                options: { temperature: 0.3, num_predict: 400 }
            }, { timeout: this.timeout });

            return response.data.response || null;
        } catch (error) {
            console.log(`Ollama unavailable (${error.message}) — using rule-based analysis`);
            return null;
        }
    }

    _buildPrompt(context, evidence) {
        return [
            'You are ProTrader Copilot, a trading analysis assistant. You MUST base your analysis ONLY on the structured data provided. Do not invent prices, indicators, or events.',
            '',
            'STRUCTURED MARKET CONTEXT:',
            JSON.stringify({
                symbol: context.symbol,
                price: evidence.marketConditions.price,
                indicators: evidence.indicatorsUsed,
                regime: evidence.marketConditions.regime,
                volatility: evidence.marketConditions.volatility,
                relativeVolume: evidence.marketConditions.relativeVolume,
                portfolio: evidence.portfolioContext,
                risks: evidence.risks,
                counterarguments: evidence.counterarguments
            }, null, 2),
            '',
            'TASK: In 150 words or less, explain:',
            '1. What is happening with this instrument?',
            '2. Why is it happening (based on the evidence)?',
            '3. What risks exist?',
            '4. What would invalidate the current thesis?',
            '',
            'Use cautious language like "Technical conditions are supportive, but elevated volatility increases downside risk."',
            'Never give blind BUY/SELL commands. End with a data timestamp disclaimer.'
        ].join('\n');
    }
}

module.exports = AICopilot;